prod:
  logger:
    class:   sfNoLogger
    param:
      level:   err
      loggers: ~
cli:
  controller:
    class: sfConsoleController
  request:
    class: sfConsoleRequest
  response:
    class: sfConsoleResponse

test:
  storage:
    class: sfSessionTestStorage

all:
#  controller:
#    class: sfFrontWebController
#
#  request:
#    class: sfWebRequest
#
#  response:
#    class: sfWebResponse
#
#  user:
#    class: myUser
#
#  storage:
#    class: sfSessionStorage
#    param:
#      session_name: symfony
  storage:
    class: sfSessionStorage
    param:
      session_name: ullright
#
#  view_cache:
#    class: sfFileCache
#    param:
#      automatic_cleaning_factor: 0
#      prefix:                    %SF_APP_DIR%
#      cache_dir:                %SF_TEMPLATE_CACHE_DIR%
#
#
  i18n:
    class: sfI18N
    param:
      source:              XLIFF
#      debug:               off
#      untranslated_prefix: "[T]"
#      untranslated_suffix: "[/T]"
#      cache:
#        class: sfFileCache
#        param:
#          automatic_cleaning_factor: 0
#          cache_dir:                 %SF_I18N_CACHE_DIR%
#          lifetime:                  86400
#          prefix:                    %SF_APP_DIR%

  all:
    user:
    class: myUser
    param:
      timeout:     1000000     # session timeout in seconds